labels:
  redis:
    name: redis
  postgres:
    name: postgres
  backend:
    name: backend
  consumer:
    name: consumer
  indexer:
    name: indexer

ports:
  redis: 6379
  postgres: 5432
  backend: 8080
  consumer: 8081

volumes:
  redis:
    name: redis-data
    class: standard-rwo
    storage: 10Gi
  postgres:
    name: postgres-data
    class: standard-rwo
    storage: 50Gi

deployments:
  sha: aabbccdd
  redis:
    replicas: 1
    image: redis
    tag: 7.2.4-alpine
  postgres:
    replicas: 1
    image: postgres
    tag: 14.11-alpine
  backend:
    replicas: 1
    image: brandonjroberts/foc-fun-backend
  consumer:
    replicas: 1
    image: brandonjroberts/foc-fun-consumer
  indexer:
    replicas: 1
    image: brandonjroberts/foc-fun-indexer

postgres:
  db: foc-fun-db
  user: foc-fun-user
  password: FocFunPassword1234

apibara:
  #streamUrl: https://mainnet.starknet.a5a.ch
  streamUrl: https://sepolia.starknet.a5a.ch
  indexerId: foc-fun-indexer-id
  authToken: dna_aabbcc

contracts:
  focFunRegistryContract: 0x06c28e3b1442ea866c0a29b2094e76983a6260d5e54216a5d12cdd676f65a6e5
