apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: foc-fun-static-ip
    networking.gke.io/managed-certificates: foc-fun-managed-cert
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.labels.backend.name }}
            port:
              number: {{ .Values.ports.backend }}
