apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.labels.backend.name }}-secret
  labels:
    app: {{ .Values.labels.backend.name }}
data:
  FOC_FUN_REGISTRY_CONTRACT: {{ .Values.contracts.focFunRegistryContract }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
