apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.labels.indexer.name }}-secret
  labels:
    app: {{ .Values.labels.indexer.name }}
data:
  FOC_FUN_REGISTRY_CONTRACT: {{ .Values.contracts.focFunRegistryContract }}
  CONSUMER_TARGET_URL: http://{{ .Values.labels.consumer.name }}.foc-fun-sepolia.svc.cluster.local:{{ .Values.ports.consumer }}/consume-indexer-msg
  APIBARA_STREAM_URL: {{ .Values.apibara.streamUrl }}
  AUTH_TOKEN: {{ .Values.apibara.authToken }}
  PERSIST_TO_REDIS: redis://{{ .Values.labels.redis.name }}.foc-fun-sepolia.svc.cluster.local:{{ .Values.ports.redis }}
  INDEXER_ID: {{ .Values.apibara.indexerId }}
