apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.labels.consumer.name }}-secret
  labels:
    app: {{ .Values.labels.consumer.name }}
data:
  FOC_FUN_REGISTRY_CONTRACT: {{ .Values.contracts.focFunRegistryContract }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
